export interface Prospect {
  id: number;
  name: string;
  category: 'Golf' | 'Marina' | 'Hardware' | 'Resort Gift';
  region:
    'Okanagan' | 'Shuswap' | 'Vancouver Island' | 'Sea-to-Sky' | 'Kootenays' | 'Fraser Valley';
  city: string;
  address: string;
  phone: string;
  fit: string;
}

export const PROSPECTS_DATA: Prospect[] = [
  // Okanagan Valley (1 - 45)
  {
    id: 1,
    name: 'Kelowna Golf & Country Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '1297 Glenmore Dr',
    phone: '250-762-2531',
    fit: 'Semi-private course with high retiree male membership; stocks resort lifestyle apparel.',
  },
  {
    id: 2,
    name: 'Penticton Golf & Country Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Penticton',
    address: '280 Eckhardt Ave W',
    phone: '250-492-8727',
    fit: 'Busy 18-hole championship course in senior demographic hub.',
  },
  {
    id: 3,
    name: 'Shannon Lake Golf Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'West Kelowna',
    address: '2439 Shannon Lake Rd',
    phone: '250-768-4653',
    fit: 'Popular public course pro shop carrying casual golf graphic tees and hats.',
  },
  {
    id: 4,
    name: 'Osoyoos Golf Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Osoyoos',
    address: '12300 Golf Course Dr',
    phone: '250-495-7003',
    fit: '36-hole resort course with active senior leagues and high tourist foot traffic.',
  },
  {
    id: 5,
    name: "Gallagher's Canyon Golf Club",
    category: 'Golf',
    region: 'Okanagan',
    city: 'Kelowna',
    address: "4320 Gallagher's Dr W",
    phone: '250-861-4240',
    fit: "GolfBC resort destination pro shop with premium men's casual apparel.",
  },
  {
    id: 6,
    name: 'Vernon Golf & Country Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Vernon',
    address: '800 Kalamazoo Crt',
    phone: '250-542-9181',
    fit: 'Established club with active retiree membership.',
  },
  {
    id: 7,
    name: 'Tower Ranch Golf Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '1855 Tower Ranch Blvd',
    phone: '250-491-8211',
    fit: "Championship public course with pro shop carrying men's gifts and caps.",
  },
  {
    id: 8,
    name: 'Penticton Yacht Club and Marina',
    category: 'Marina',
    region: 'Okanagan',
    city: 'Penticton',
    address: '293 Marina Way',
    phone: '250-770-2000',
    fit: 'Full-service marina on Okanagan Lake with retail boat shop.',
  },
  {
    id: 9,
    name: 'Okanagan Lake Marina & Boat Rentals',
    category: 'Marina',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '1300 Water St',
    phone: '250-762-2628',
    fit: 'Downtown Kelowna waterfront shop selling boater apparel and novelties.',
  },
  {
    id: 10,
    name: 'Peachland Marina Store',
    category: 'Marina',
    region: 'Okanagan',
    city: 'Peachland',
    address: '5864 Beach Ave',
    phone: '250-767',
    fit: 'Lakeside shop popular with retired boaters and tourists.',
  },
  {
    id: 11,
    name: 'Summerland Waterfront Resort Gift Shop',
    category: 'Resort Gift',
    region: 'Okanagan',
    city: 'Summerland',
    address: '13011 Lakeshore Dr S',
    phone: '250-494-8180',
    fit: 'Resort gift shop catering to vacationing retirees and families.',
  },
  {
    id: 12,
    name: 'Penticton Home Hardware Building Centre',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Penticton',
    address: '150 Station St',
    phone: '250-493-2800',
    fit: "Large dealer-owned store with dedicated men's workwear and gifts.",
  },
  {
    id: 13,
    name: 'Osoyoos Home Building Centre',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Osoyoos',
    address: '9120 348th Ave',
    phone: '250-495-6501',
    fit: 'Busy dealer location serving retirees, vineyard workers, and DIYers.',
  },
  {
    id: 14,
    name: 'West Kelowna Home Hardware',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'West Kelowna',
    address: '2541 Main St',
    phone: '250-768-3121',
    fit: 'Independent dealer store with active hardware and novelty customer base.',
  },
  {
    id: 15,
    name: 'Kelowna Home Hardware',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '1650 Springfield Rd',
    phone: '250-860-2525',
    fit: "High-volume dealer store carrying tools, workwear, and men's gifts.",
  },
  {
    id: 16,
    name: 'Vernon Home Building Centre',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Vernon',
    address: '4601 27th St',
    phone: '250-545-5384',
    fit: 'Major dealer location with clothing section.',
  },
  {
    id: 17,
    name: 'Oliver Home Hardware',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Oliver',
    address: '34812 91st St',
    phone: '250-498-3310',
    fit: 'Rural town dealer serving active retirees and agriculturalists.',
  },
  {
    id: 18,
    name: "Buckerfield's Kelowna",
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '1889 Springfield Rd',
    phone: '250-860-2346',
    fit: 'Country store selling outdoor apparel, Tilley hats, and gifts.',
  },
  {
    id: 19,
    name: 'Peavey Mart Penticton',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Penticton',
    address: '270 Riverside Dr',
    phone: '250-492-0700',
    fit: 'Farm and ranch supply store with large apparel aisle.',
  },
  {
    id: 20,
    name: 'Black Mountain Golf Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '575 Black Mountain Dr',
    phone: '250-765-6890',
    fit: "Popular public golf pro shop stocking casual men's clothing.",
  },
  {
    id: 21,
    name: 'Shadow Ridge Golf Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '3726 Garman Rd',
    phone: '250-765-7777',
    fit: 'Friendly public course with senior leagues.',
  },
  {
    id: 22,
    name: 'Two Eagles Golf Course & Academy',
    category: 'Golf',
    region: 'Okanagan',
    city: 'West Kelowna',
    address: '3509 Carrington Rd',
    phone: '250-768-0080',
    fit: 'High-turnover pro shop in senior residential area.',
  },
  {
    id: 23,
    name: 'Sunset Ranch Golf & Country Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '5101 Sunset Ranch Dr',
    phone: '250-765-7700',
    fit: 'Scenic course pro shop selling graphic tees and caps.',
  },
  {
    id: 24,
    name: 'The Harvest Golf Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '2725 K. L. O. Rd',
    phone: '250-862-3103',
    fit: 'Resort style pro shop catering to local and visiting golfers.',
  },
  {
    id: 25,
    name: 'Fairview Mountain Golf Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Oliver',
    address: '1310 Fairview Rd',
    phone: '250-498-6050',
    fit: 'Top-rated Okanagan course with high pro shop apparel sales.',
  },
  {
    id: 26,
    name: "NK'MIP Canyon Desert Golf Course",
    category: 'Golf',
    region: 'Okanagan',
    city: 'Oliver',
    address: '6831 Tuckskwawnt Dr',
    phone: '250-498-2880',
    fit: 'Resort course pro shop carrying summer lifestyle gear.',
  },
  {
    id: 27,
    name: 'Spallumcheen Golf & Country Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Vernon',
    address: '9401 Highway 97',
    phone: '250-545-5824',
    fit: "27-hole facility with high senior men's participation.",
  },
  {
    id: 28,
    name: 'Predator Ridge Resort Shop',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Vernon',
    address: '301 Village Centre Pl',
    phone: '250-542-3436',
    fit: 'Premier resort retail store stocking golf and lifestyle brands.',
  },
  {
    id: 29,
    name: 'Hirsch Creek Golf & Winter Club',
    category: 'Golf',
    region: 'Okanagan',
    city: 'Vernon',
    address: '2000 Kingfisher Ave',
    phone: '250-632-4242',
    fit: 'Community club pro shop.',
  },
  {
    id: 30,
    name: 'Kelowna Marina Store & Watersports',
    category: 'Marina',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '1500 Water St',
    phone: '250-764-0808',
    fit: 'Busy waterfront marina selling boater tees and hats.',
  },
  {
    id: 31,
    name: 'Shelter Cove Marina Store',
    category: 'Marina',
    region: 'Okanagan',
    city: 'West Kelowna',
    address: '4400 Westside Rd',
    phone: '250-769-3333',
    fit: 'Lakefront marina store serving weekend boaters.',
  },
  {
    id: 32,
    name: 'Vernon Yacht Club Retail Corner',
    category: 'Marina',
    region: 'Okanagan',
    city: 'Vernon',
    address: '7910 Okanagan Landing Rd',
    phone: '250-545-5518',
    fit: 'Yacht club pro shop catering to older boat owners.',
  },
  {
    id: 33,
    name: 'Okanagan Centre Marina Shop',
    category: 'Marina',
    region: 'Okanagan',
    city: 'Lake Country',
    address: '11230 Okanagan Centre Rd W',
    phone: '250-766-2005',
    fit: 'Lakeside marina store selling boating gifts.',
  },
  {
    id: 34,
    name: 'Wood Lake Marina Store',
    category: 'Marina',
    region: 'Okanagan',
    city: 'Oyama',
    address: '11811 Lake Country Way',
    phone: '250-766-2220',
    fit: 'Popular summer boat shop stocking graphic apparel.',
  },
  {
    id: 35,
    name: 'Downtown Kelowna Souvenir & Gift',
    category: 'Resort Gift',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '505 Bernard Ave',
    phone: '250-868-3311',
    fit: 'Tourist gift store selling Canadian and Okanagan humor tees.',
  },
  {
    id: 36,
    name: 'Okanagan Oasis Gifts',
    category: 'Resort Gift',
    region: 'Okanagan',
    city: 'Penticton',
    address: '212 Main St',
    phone: '250-493-1122',
    fit: 'Main street shop targeting vacationers and active retirees.',
  },
  {
    id: 37,
    name: 'Vernon Tourist Gift Depot',
    category: 'Resort Gift',
    region: 'Okanagan',
    city: 'Vernon',
    address: '3001 30th Ave',
    phone: '250-542-8811',
    fit: "High foot-traffic store with men's novelty apparel.",
  },
  {
    id: 38,
    name: 'Man Cave Gifts & Gadgets',
    category: 'Resort Gift',
    region: 'Okanagan',
    city: 'Kelowna',
    address: '2271 Harvey Ave',
    phone: '250-860-4433',
    fit: "Dedicated men's gift shop selling humor tees and mugs.",
  },
  {
    id: 39,
    name: 'Osoyoos Desert Gift Shop',
    category: 'Resort Gift',
    region: 'Okanagan',
    city: 'Osoyoos',
    address: '8308 Main St',
    phone: '250-495-2244',
    fit: 'Busy resort town store carrying casual summer clothing.',
  },
  {
    id: 40,
    name: 'Peachland Lakeside Gifts',
    category: 'Resort Gift',
    region: 'Okanagan',
    city: 'Peachland',
    address: '5878 Beach Ave',
    phone: '250-767-1133',
    fit: 'Beachfront gift shop selling lake lifestyle apparel.',
  },
  {
    id: 41,
    name: 'Lake Country Home Hardware',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Lake Country',
    address: '10051 Hwy 97',
    phone: '250-766-2321',
    fit: 'Dealer-owned hardware store serving local retirees.',
  },
  {
    id: 42,
    name: 'Armstrong Home Hardware',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Armstrong',
    address: '2550 Pleasant Valley Rd',
    phone: '250-546-3002',
    fit: "Rural dealer with strong workwear and men's gift sales.",
  },
  {
    id: 43,
    name: 'Enderby Home Hardware',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Enderby',
    address: '606 Cliff Ave',
    phone: '250-838-7000',
    fit: 'Community dealer store catering to outdoor enthusiasts.',
  },
  {
    id: 44,
    name: 'Keremeos Home Building Centre',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Keremeos',
    address: '604 7th Ave',
    phone: '250-499-5512',
    fit: 'Valley dealer store with casual apparel rack.',
  },
  {
    id: 45,
    name: 'Princeton Home Hardware',
    category: 'Hardware',
    region: 'Okanagan',
    city: 'Princeton',
    address: '114 Bridge St',
    phone: '250-295-6938',
    fit: 'Independent dealer store serving fishermen and DIYers.',
  },

  // Shuswap & Thompson-Nicola (46 - 80)
  {
    id: 46,
    name: 'Salmon Arm Golf Club',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Salmon Arm',
    address: '3641 30th Ave NE',
    phone: '250-832-4727',
    fit: 'Highly rated 27-hole course with active senior membership.',
  },
  {
    id: 47,
    name: 'Shuswap Lake Golf Course',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Blind Bay',
    address: '2425 Blind Bay Rd',
    phone: '250-675-2315',
    fit: 'Resort public course catering to retired cabin owners.',
  },
  {
    id: 48,
    name: 'Hyde Mountain Golf Resort',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Sicamous',
    address: '985 Old Spallumcheen Rd',
    phone: '250-836 4653',
    fit: 'Shuswap Lake golf resort pro shop.',
  },
  {
    id: 49,
    name: 'Rivershore Golf Links',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Kamloops',
    address: '330 Rivershore Dr',
    phone: '250-573-4622',
    fit: 'Robert Trent Jones Sr. design course with busy pro shop.',
  },
  {
    id: 50,
    name: 'Kamloops Golf & Country Club',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Kamloops',
    address: '3125 Golf Course Rd',
    phone: '250-376-8020',
    fit: 'Oldest club in Kamloops with high senior participation.',
  },
  {
    id: 51,
    name: 'Tobiano Golf Course Shop',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Kamloops',
    address: '3883 Tobiano Way',
    phone: '250-434-7373',
    fit: 'Destination resort pro shop selling golf lifestyle apparel.',
  },
  {
    id: 52,
    name: 'Talking Rock Golf Course',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Chase',
    address: '1663 Little Shuswap Lake Rd',
    phone: '250-679-3090',
    fit: 'Resort course pro shop on Little Shuswap Lake.',
  },
  {
    id: 53,
    name: 'Sicamous Marina Store & Rentals',
    category: 'Marina',
    region: 'Shuswap',
    city: 'Sicamous',
    address: '1211 Riverside Ave',
    phone: '250-836 2433',
    fit: 'Houseboat capital marina store selling boating humor tees.',
  },
  {
    id: 54,
    name: 'Twin Anchors Marine Store',
    category: 'Marina',
    region: 'Shuswap',
    city: 'Sicamous',
    address: '101 Martin St',
    phone: '250-836-2450',
    fit: 'Major Shuswap houseboat marina retail outlet.',
  },
  {
    id: 55,
    name: "Captain's Village Marina Store",
    category: 'Marina',
    region: 'Shuswap',
    city: 'Scotch Creek',
    address: '3870 Squilax-Anglemont Rd',
    phone: '250-955-2424',
    fit: 'Prime North Shuswap lake marina selling boat lifestyle gear.',
  },
  {
    id: 56,
    name: 'Shuswap Marina Store',
    category: 'Marina',
    region: 'Shuswap',
    city: 'Blind Bay',
    address: '2233 Blind Bay Rd',
    phone: '250-675-2244',
    fit: 'Blind Bay lakefront store stocking caps and t-shirts.',
  },
  {
    id: 57,
    name: 'Salmon Arm Home Building Centre',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Salmon Arm',
    address: '1150 10th Ave SW',
    phone: '250-832-8061',
    fit: 'Major Shuswap dealer store with dedicated workwear section.',
  },
  {
    id: 58,
    name: 'Kamloops Home Hardware Building Centre',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Kamloops',
    address: '1325 Halton Crt',
    phone: '250-377-7200',
    fit: "Large independent dealer carrying tools and men's apparel.",
  },
  {
    id: 59,
    name: 'Sicamous Home Building Centre',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Sicamous',
    address: '201 Main St',
    phone: '250-836-2551',
    fit: 'Lakeside dealer serving boaters, retirees, and local trades.',
  },
  {
    id: 60,
    name: 'Chase Home Hardware',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Chase',
    address: '825 Shuswap Ave',
    phone: '250-679-3112',
    fit: 'Community dealer store with popular gift display.',
  },
  {
    id: 61,
    name: 'Merritt Home Hardware',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Merritt',
    address: '1701 Voght St',
    phone: '250-378-4215',
    fit: 'Nicola Valley dealer serving ranchers, retirees, and DIYers.',
  },
  {
    id: 62,
    name: "Buckerfield's Kamloops",
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Kamloops',
    address: '810 Lagimodiere Way',
    phone: '250-372-2400',
    fit: 'Farm and country lifestyle store selling workwear and hats.',
  },
  {
    id: 63,
    name: 'Peavey Mart Kamloops',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Kamloops',
    address: '1800 Springhill Dr',
    phone: '250-374-1223',
    fit: 'Regional farm supply store stocking graphic tees and caps.',
  },
  {
    id: 64,
    name: 'Eagle Point Golf Resort',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Kamloops',
    address: '8888 Barnhartvale Rd',
    phone: '250-573-2453',
    fit: 'Public course pro shop serving local senior golfers.',
  },
  {
    id: 65,
    name: 'Bighorn Golf & Country Club',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Kamloops',
    address: '1000 Sun Rivers Dr',
    phone: '250-571-7888',
    fit: 'Sun Rivers resort pro shop.',
  },
  {
    id: 66,
    name: 'Sun Peaks Resort Golf Shop',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Sun Peaks',
    address: '1280 Alpine Rd',
    phone: '250-578-5431',
    fit: 'Mountain resort course pro shop selling lifestyle apparel.',
  },
  {
    id: 67,
    name: 'Chinook Cove Golf Course',
    category: 'Golf',
    region: 'Shuswap',
    city: 'Barriere',
    address: '4000 Barriere Lakes Rd',
    phone: '250-672 5115',
    fit: 'North Thompson course pro shop.',
  },
  {
    id: 68,
    name: 'Lac Le Jeune Resort Store',
    category: 'Resort Gift',
    region: 'Shuswap',
    city: 'Kamloops',
    address: '56 Lac Le Jeune Rd',
    phone: '250-372-2722',
    fit: 'Lakeside fishing resort shop selling angler tees.',
  },
  {
    id: 69,
    name: 'Anglemont Marina Store',
    category: 'Marina',
    region: 'Shuswap',
    city: 'Anglemont',
    address: '2559 Lakeview Dr',
    phone: '250-955-2231',
    fit: 'North Shuswap lake store selling boating gear.',
  },
  {
    id: 70,
    name: 'Totem Marina Store',
    category: 'Marina',
    region: 'Shuswap',
    city: 'Shuswap',
    address: '2415 Blind Bay Rd',
    phone: '250-675-2322',
    fit: 'Blind Bay waterfront marina store.',
  },
  {
    id: 71,
    name: 'Salmon Arm Waterfront Gifts',
    category: 'Resort Gift',
    region: 'Shuswap',
    city: 'Salmon Arm',
    address: '141 Lakeshore Dr NE',
    phone: '250-832-9922',
    fit: 'Main street shop selling Canadian vacation apparel.',
  },
  {
    id: 72,
    name: 'Sicamous Trading Post',
    category: 'Resort Gift',
    region: 'Shuswap',
    city: 'Sicamous',
    address: '422 Main St',
    phone: '250-836-3311',
    fit: 'Tourist store carrying humor t-shirts and caps.',
  },
  {
    id: 73,
    name: 'Scotch Creek General Store',
    category: 'Resort Gift',
    region: 'Shuswap',
    city: 'Scotch Creek',
    address: '3892 Squilax-Anglemont Rd',
    phone: '250-955-2222',
    fit: 'Shuswap vacation hub store selling lake graphic tees.',
  },
  {
    id: 74,
    name: 'Sorrento General Store',
    category: 'Resort Gift',
    region: 'Shuswap',
    city: 'Sorrento',
    address: '1241 Trans-Canada Hwy',
    phone: '250-675-2121',
    fit: 'Highway store catering to summer cabin residents.',
  },
  {
    id: 75,
    name: 'Barriere Home Hardware',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Barriere',
    address: '4321 Barriere Town Rd',
    phone: '250-672 9411',
    fit: 'Community dealer store with outdoor supply aisle.',
  },
  {
    id: 76,
    name: 'Clearwater Home Hardware',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Clearwater',
    address: '211 Old Clearwater Hwy',
    phone: '250-674-3122',
    fit: 'Wells Gray park gateway dealer selling workwear and gifts.',
  },
  {
    id: 77,
    name: 'Ashcroft Home Hardware',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Ashcroft',
    address: '301 Railway Ave',
    phone: '250-453-2242',
    fit: 'Heritage town dealer store.',
  },
  {
    id: 78,
    name: 'Lillooet Home Hardware',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Lillooet',
    address: '623 Main St',
    phone: '250-256-4241',
    fit: 'Community dealer serving outdoorsmen and trades.',
  },
  {
    id: 79,
    name: 'Logan Lake Home Hardware',
    category: 'Hardware',
    region: 'Shuswap',
    city: 'Logan Lake',
    address: '118 Chartrand Ave',
    phone: '250-523-2341',
    fit: 'Mining and retiree town dealer store.',
  },
  {
    id: 80,
    name: 'Mabel Lake Resort Store',
    category: 'Resort Gift',
    region: 'Shuswap',
    city: 'Enderby',
    address: '3441 Mabel Lake Rd',
    phone: '250-838-6234',
    fit: 'Resort marina store selling lake lifestyle clothing.',
  },

  // Vancouver Island & Gulf Islands (81 - 140)
  {
    id: 81,
    name: 'Cordova Bay Golf Course',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Victoria',
    address: '5333 Cordova Bay Rd',
    phone: '250-658-4075',
    fit: 'High-end public course with premier retail pro shop.',
  },
  {
    id: 82,
    name: 'Highland Pacific Golf',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Victoria',
    address: '450 Highland Rd',
    phone: '250-478-4653',
    fit: 'Busy public pro shop in Victoria retiree corridor.',
  },
  {
    id: 83,
    name: 'Gorge Vale Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Victoria',
    address: '1005 Craigflower Rd',
    phone: '250-386-3418',
    fit: 'Traditional club with active senior membership.',
  },
  {
    id: 84,
    name: 'Morningstar Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Parksville',
    address: '525 Lowrys Rd',
    phone: '250-248-2244',
    fit: 'Parksville retiree hub course with high apparel sales.',
  },
  {
    id: 85,
    name: 'Fairwinds Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Nanoose Bay',
    address: '3730 Fairwinds Dr',
    phone: '250-468-7666',
    fit: 'Oceanfront resort course pro shop serving active retirees.',
  },
  {
    id: 86,
    name: 'Pheasant Glen Golf Resort',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Qualicum Beach',
    address: '1025 Qualicum Rd',
    phone: '250-752 8786',
    fit: 'Qualicum Beach course pro shop.',
  },
  {
    id: 87,
    name: 'Crown Isle Resort & Golf Community',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Courtenay',
    address: '399 Clubhouse Dr',
    phone: '250-703-5029',
    fit: 'Major Comox Valley resort pro shop stocking lifestyle clothing.',
  },
  {
    id: 88,
    name: 'Storey Creek Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Campbell River',
    address: '300 McGimpsey Rd',
    phone: '250-923-3670',
    fit: 'Famous Les Furber course with active pro shop.',
  },
  {
    id: 89,
    name: 'Sidney Pier Resort Gift Boutique',
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Sidney',
    address: '9805 Seaport Pl',
    phone: '250-655-9700',
    fit: 'Oceanfront resort shop in retiree-dense Sidney.',
  },
  {
    id: 90,
    name: 'Tofino Resort & Marina Store',
    category: 'Marina',
    region: 'Vancouver Island',
    city: 'Tofino',
    address: '634 Campbell St',
    phone: '250-725-3443',
    fit: 'Prime Tofino waterfront marina shop carrying coastal apparel.',
  },
  {
    id: 91,
    name: 'Pedder Bay RV Resort & Marina Store',
    category: 'Marina',
    region: 'Vancouver Island',
    city: 'Metchosin',
    address: '925 Pedder Bay Rd',
    phone: '250-478-1771',
    fit: 'Angler and boater marina shop selling fishing humor tees.',
  },
  {
    id: 92,
    name: 'French Creek Marina Store',
    category: 'Marina',
    region: 'Vancouver Island',
    city: 'Parksville',
    address: '1025 Lee Rd',
    phone: '250-248-2831',
    fit: 'Parksville-Qualicum marina store serving boaters and tourists.',
  },
  {
    id: 93,
    name: 'Oak Bay Marina Store',
    category: 'Marina',
    region: 'Vancouver Island',
    city: 'Victoria',
    address: '1327 Beach Dr',
    phone: '250-598-3366',
    fit: 'Premier Victoria marina retail shop.',
  },
  {
    id: 94,
    name: 'Sidney Home Hardware Building Centre',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Sidney',
    address: '2356 Beacon Ave',
    phone: '250-656 1123',
    fit: 'Beacon Ave store with large gift and clothing section.',
  },
  {
    id: 95,
    name: 'Parksville Home Hardware',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Parksville',
    address: '142 Island Hwy E',
    phone: '250-248 3221',
    fit: 'Retiree hub dealer store with dedicated gift aisle.',
  },
  {
    id: 96,
    name: 'Qualicum Beach Home Hardware',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Qualicum Beach',
    address: '135 Second Ave W',
    phone: '250-752-9831',
    fit: "Main street dealer store in Canada's oldest demographic town.",
  },
  {
    id: 97,
    name: 'Sooke Home Building Centre',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Sooke',
    address: '2036 Shield Rd',
    phone: '250-642 6366',
    fit: 'West Coast dealer serving fishermen, trades, and DIYers.',
  },
  {
    id: 98,
    name: 'Campbell River Home Hardware',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Campbell River',
    address: '1330 Homewood Rd',
    phone: '250-287 9551',
    fit: 'Salmon capital dealer store with large outdoor department.',
  },
  {
    id: 99,
    name: "Buckerfield's Saanichton",
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Saanichton',
    address: '1970 Keating Cross Rd',
    phone: '250-652 9188',
    fit: 'Island country store selling Tilley hats, workwear, and gifts.',
  },
  {
    id: 100,
    name: "Buckerfield's Nanaimo",
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Nanaimo',
    address: '1-1277 Island Hwy S',
    phone: '250-753-4221',
    fit: 'High-traffic country lifestyle store.',
  },
  {
    id: 101,
    name: 'Peavey Mart Duncan',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Duncan',
    address: '2980 Boys Rd',
    phone: '250-746-9552',
    fit: 'Cowichan Valley farm store stocking graphic t-shirts.',
  },
  {
    id: 102,
    name: 'Cowichan Golf & Country Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Duncan',
    address: '4955 River Rd',
    phone: '250-746-5333',
    fit: 'Valley club pro shop.',
  },
  {
    id: 103,
    name: 'Arbutus Ridge Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Cobble Hill',
    address: '3515 Telegraph Rd',
    phone: '250-743-5100',
    fit: 'GolfBC resort pro shop in active retiree community.',
  },
  {
    id: 104,
    name: 'Nanaimo Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Nanaimo',
    address: '2800 Highland Blvd',
    phone: '250-758 6331',
    fit: 'Traditional club with strong retail sales.',
  },
  {
    id: 105,
    name: 'Eaglecrest Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Qualicum Beach',
    address: '2035 Island Hwy W',
    phone: '250-752 6311',
    fit: 'Qualicum oceanfront course pro shop.',
  },
  {
    id: 106,
    name: 'Sunnydale Golf & Country Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Courtenay',
    address: '5291 N Island Hwy',
    phone: '250-334 3251',
    fit: 'Comox Valley public course pro shop.',
  },
  {
    id: 107,
    name: 'Campbell River Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Campbell River',
    address: '700 Peterson Rd',
    phone: '250-287 7885',
    fit: 'Modern course pro shop carrying casual golf apparel.',
  },
  {
    id: 108,
    name: 'Quadra Island Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Quadra Island',
    address: '1015 Quality Rd',
    phone: '250-285 2811',
    fit: 'Island golf shop popular with retirees.',
  },
  {
    id: 109,
    name: 'Sooke Harbour Marina Store',
    category: 'Marina',
    region: 'Vancouver Island',
    city: 'Sooke',
    address: '6971 West Coast Rd',
    phone: '250-642 3231',
    fit: 'Fishing marina store selling boater humor tees.',
  },
  {
    id: 110,
    name: 'Maple Bay Marina Store',
    category: 'Marina',
    region: 'Vancouver Island',
    city: 'Duncan',
    address: '6145 Genoa Bay Rd',
    phone: '250-746 8482',
    fit: 'Cowichan Bay marina boutique.',
  },
  {
    id: 111,
    name: 'Schoener Cove Marina Store',
    category: 'Marina',
    region: 'Vancouver Island',
    city: 'Nanoose Bay',
    address: '3691 Schooner House Rd',
    phone: '250-468 9873',
    fit: 'Fairwinds community marina store.',
  },
  {
    id: 112,
    name: 'Comox Valley Marina Store',
    category: 'Marina',
    region: 'Vancouver Island',
    city: 'Comox',
    address: '1801 Beaufort Ave',
    phone: '250-339 2931',
    fit: 'Comox harbour marina shop.',
  },
  {
    id: 113,
    name: 'Discovery Harbour Marina Store',
    category: 'Marina',
    region: 'Vancouver Island',
    city: 'Campbell River',
    address: '1374 Island Hwy',
    phone: '250-287 2622',
    fit: 'Campbell River waterfront store.',
  },
  {
    id: 114,
    name: 'Salt Spring Marina Store',
    category: 'Marina',
    region: 'Vancouver Island',
    city: 'Ganges',
    address: '124 Upper Ganges Rd',
    phone: '250-537 5810',
    fit: 'Ganges harbour store selling island lifestyle clothing.',
  },
  {
    id: 115,
    name: 'Beacon Gifts Sidney',
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Sidney',
    address: '2401 Beacon Ave',
    phone: '250-656-2112',
    fit: 'High foot-traffic gift store in retiree haven.',
  },
  {
    id: 116,
    name: 'Victoria Inner Harbour Gifts',
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Victoria',
    address: '812 Government St',
    phone: '250-384-3322',
    fit: 'Prime tourist store carrying Canadian graphic tees.',
  },
  {
    id: 117,
    name: 'Cowichan Bay Trading Co.',
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Cowichan Bay',
    address: '1681 Cowichan Bay Rd',
    phone: '250-748 3211',
    fit: 'Waterfront tourist village boutique.',
  },
  {
    id: 118,
    name: 'Chemainus Gifts & Souvenirs',
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Chemainus',
    address: '9750 Chemainus Rd',
    phone: '250-246 3322',
    fit: 'Mural town gift store catering to bus tours and retirees.',
  },
  {
    id: 119,
    name: 'Coombs Country Market Gift Shop',
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Coombs',
    address: '2326 Alberni Hwy',
    phone: '250-248 8001',
    fit: 'Famous Goats on the Roof market selling humor t-shirts.',
  },
  {
    id: 120,
    name: 'Parksville Boardwalk Gifts',
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Parksville',
    address: '182 Craig St',
    phone: '250-248 1122',
    fit: 'Beachfront gift shop selling vacation clothing.',
  },
  {
    id: 121,
    name: 'Qualicum Beach Fudge & Gift Shop',
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Qualicum Beach',
    address: '162 Second Ave W',
    phone: '250-752 3311',
    fit: 'Main street store carrying novelty gifts.',
  },
  {
    id: 122,
    name: 'Tofino House of Gifts',
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Tofino',
    address: '301 Campbell St',
    phone: '250-725 3311',
    fit: 'Tourist shop selling coastal lifestyle t-shirts.',
  },
  {
    id: 123,
    name: 'Ucluelet Trading Post',
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Ucluelet',
    address: '1972 Peninsula Rd',
    phone: '250-726 2211',
    fit: 'West Coast gift shop carrying outdoor graphic tees.',
  },
  {
    id: 124,
    name: "Ganges Mouat's Trading Co.",
    category: 'Resort Gift',
    region: 'Vancouver Island',
    city: 'Salt Spring Island',
    address: '106 Fulford-Ganges Rd',
    phone: '250-537-5593',
    fit: 'Historic department store on Salt Spring Island.',
  },
  {
    id: 125,
    name: 'Duncan Home Hardware',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Duncan',
    address: '285 Trunk Rd',
    phone: '250-746 5141',
    fit: 'Cowichan Valley dealer store.',
  },
  {
    id: 126,
    name: 'Ladysmith Home Hardware',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Ladysmith',
    address: '132 High St',
    phone: '250-245 3121',
    fit: 'Main street dealer store.',
  },
  {
    id: 127,
    name: 'Nanaimo Coal Tyee Home Hardware',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Nanaimo',
    address: '2124 Bowen Rd',
    phone: '250-758 3911',
    fit: 'Busy independent dealer store.',
  },
  {
    id: 128,
    name: 'Courtenay Home Hardware',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Courtenay',
    address: '2125 Cumberland Rd',
    phone: '250-334 3131',
    fit: 'Comox Valley dealer store.',
  },
  {
    id: 129,
    name: 'Port Alberni Home Hardware',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Port Alberni',
    address: '4680 Johnston Rd',
    phone: '250-723 5641',
    fit: 'Alberni Valley dealer serving anglers and outdoorsmen.',
  },
  {
    id: 130,
    name: 'Port Hardy Home Hardware',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Port Hardy',
    address: '8950 Granville St',
    phone: '250-949 6612',
    fit: 'North Island dealer store.',
  },
  {
    id: 131,
    name: 'Salt Spring Home Hardware',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Salt Spring Island',
    address: '342 Lower Ganges Rd',
    phone: '250-537 5521',
    fit: 'Island dealer store with gift section.',
  },
  {
    id: 132,
    name: "Buckerfield's Parksville",
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Parksville',
    address: '1295 Island Hwy E',
    phone: '250-248 3243',
    fit: 'Country store selling hats and outdoorsmen gifts.',
  },
  {
    id: 133,
    name: 'Peavey Mart Campbell River',
    category: 'Hardware',
    region: 'Vancouver Island',
    city: 'Campbell River',
    address: '1400 Island Hwy',
    phone: '250-286 1142',
    fit: 'Farm supply store stocking graphic tees.',
  },
  {
    id: 134,
    name: 'Bear Mountain Golf Resort Shop',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Langford',
    address: '1997 Country Club Way',
    phone: '250-391 7160',
    fit: '36-hole Nicklaus design resort pro shop.',
  },
  {
    id: 135,
    name: 'Olympic View Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Victoria',
    address: '643 Latoria Rd',
    phone: '250-474 3673',
    fit: 'GolfBC course pro shop.',
  },
  {
    id: 136,
    name: 'Cedar Hill Golf Course',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Victoria',
    address: '1400 Derby Rd',
    phone: '250-475 7151',
    fit: 'Muni course with high senior participation.',
  },
  {
    id: 137,
    name: 'March Meadows Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Honeymoon Bay',
    address: '10283 South Shore Rd',
    phone: '250-749 6311',
    fit: 'Cowichan Lake pro shop.',
  },
  {
    id: 138,
    name: 'Alberni Golf Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Port Alberni',
    address: '6421 Cherry Creek Rd',
    phone: '250-723 5422',
    fit: 'Port Alberni pro shop serving local retirees.',
  },
  {
    id: 139,
    name: 'Qualicum Beach Golf Course',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Qualicum Beach',
    address: '469 Memorial Ave',
    phone: '250-752 6312',
    fit: 'Historic seaside 9-hole course pro shop.',
  },
  {
    id: 140,
    name: 'Pender Island Golf & Country Club',
    category: 'Golf',
    region: 'Vancouver Island',
    city: 'Pender Island',
    address: '158 Field Rd',
    phone: '250-629 6659',
    fit: 'Gulf Island pro shop catering to local retirees.',
  },

  // Sea-to-Sky & Sunshine Coast (141 - 175)
  {
    id: 141,
    name: 'Whistler Golf Club Pro Shop',
    category: 'Golf',
    region: 'Sea-to-Sky',
    city: 'Whistler',
    address: '4001 Whistler Way',
    phone: '604-932-3280',
    fit: 'Arnold Palmer design course with premier retail store.',
  },
  {
    id: 142,
    name: 'Nicklaus North Golf Course Shop',
    category: 'Golf',
    region: 'Sea-to-Sky',
    city: 'Whistler',
    address: '8080 Nicklaus North Blvd',
    phone: '604-938-9898',
    fit: 'GolfBC resort pro shop stocking high-end casual wear.',
  },
  {
    id: 143,
    name: 'Fairmont Chateau Whistler Golf Club',
    category: 'Golf',
    region: 'Sea-to-Sky',
    city: 'Whistler',
    address: '4612 Blackcomb Way',
    phone: '604-938-2092',
    fit: 'Luxury resort pro shop.',
  },
  {
    id: 144,
    name: 'Squamish Valley Golf Club',
    category: 'Golf',
    region: 'Sea-to-Sky',
    city: 'Squamish',
    address: '2458 Mamquam Rd',
    phone: '604-898 9691',
    fit: 'Busy public course pro shop in growing active town.',
  },
  {
    id: 145,
    name: 'Pemberton Valley Golf Course',
    category: 'Golf',
    region: 'Sea-to-Sky',
    city: 'Pemberton',
    address: '1583 Airport Rd',
    phone: '604-894 6197',
    fit: 'Scenic valley course pro shop.',
  },
  {
    id: 146,
    name: 'Furry Creek Golf & Country Club',
    category: 'Golf',
    region: 'Sea-to-Sky',
    city: 'Furry Creek',
    address: '150 Furry Creek Dr',
    phone: '604-896-2224',
    fit: 'Famous Howe Sound resort course pro shop.',
  },
  {
    id: 147,
    name: 'Gibsons Building Supplies / Home Hardware',
    category: 'Hardware',
    region: 'Sea-to-Sky',
    city: 'Gibsons',
    address: '924 Gibsons Way',
    phone: '604-886-2221',
    fit: 'Major Sunshine Coast dealer with large gift aisle.',
  },
  {
    id: 148,
    name: 'Sechelt Home Hardware Building Centre',
    category: 'Hardware',
    region: 'Sea-to-Sky',
    city: 'Sechelt',
    address: '5600 Sunshine Coast Hwy',
    phone: '604-885-1212',
    fit: 'High-volume dealer store in retiree hub.',
  },
  {
    id: 149,
    name: 'Squamish Home Building Centre',
    category: 'Hardware',
    region: 'Sea-to-Sky',
    city: 'Squamish',
    address: '39331 Queens Way',
    phone: '604-898 3616',
    fit: 'Dealer store serving active tradesmen and outdoorsmen.',
  },
  {
    id: 150,
    name: 'Pemberton Home Hardware',
    category: 'Hardware',
    region: 'Sea-to-Sky',
    city: 'Pemberton',
    address: '7398 Molyneux Rd',
    phone: '604-894-6240',
    fit: 'Community dealer store.',
  },
  {
    id: 151,
    name: 'Gibsons Landing Marina Store',
    category: 'Marina',
    region: 'Sea-to-Sky',
    city: 'Gibsons',
    address: "400 Smitty's Lane",
    phone: '604-886 2121',
    fit: 'Gibsons harbour marina shop selling boater apparel.',
  },
  {
    id: 152,
    name: 'Secret Cove Marina Store',
    category: 'Marina',
    region: 'Sea-to-Sky',
    city: 'Halfmoon Bay',
    address: '5411 Secret Cove Rd',
    phone: '604-885-5533',
    fit: 'Resort marina store catering to summer yachting clients.',
  },
  {
    id: 153,
    name: 'Pender Harbour Marina Store',
    category: 'Marina',
    region: 'Sea-to-Sky',
    city: 'Madeira Park',
    address: '12827 Sunshine Coast Hwy',
    phone: '604-883 2345',
    fit: 'Pender Harbour boating hub store.',
  },
  {
    id: 154,
    name: 'Squamish Harbour Marina Store',
    category: 'Marina',
    region: 'Sea-to-Sky',
    city: 'Squamish',
    address: '37778 Loggers Lane',
    phone: '604-892 3232',
    fit: 'Waterfront marina shop.',
  },
  {
    id: 155,
    name: 'Gibsons Landing Waterfront Gifts',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'Gibsons',
    address: '287 Gower Point Rd',
    phone: '604-886-3322',
    fit: 'Heritage landing store with Canadian humor tees.',
  },
  {
    id: 156,
    name: 'Sechelt Inlet Gifts',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'Sechelt',
    address: '5500 Cowrie St',
    phone: '604-885 3311',
    fit: 'Main street shop targeting active retirees.',
  },
  {
    id: 157,
    name: 'Whistler Casual Apparel & Gifts',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'Whistler',
    address: '4293 Mountain Square',
    phone: '604-932-4111',
    fit: 'Whistler Village store selling resort graphic t-shirts.',
  },
  {
    id: 158,
    name: 'Squamish Adventure Centre Gift Shop',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'Squamish',
    address: '38551 Loggers Lane',
    phone: '604-815-5084',
    fit: 'Highway visitor centre shop selling outdoor graphic tees.',
  },
  {
    id: 159,
    name: 'Madeira Park Trading Post',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'Madeira Park',
    address: '12831 Madeira Park Rd',
    phone: '604-883 2211',
    fit: 'Sunshine Coast gift shop.',
  },
  {
    id: 160,
    name: 'Powell River Home Hardware',
    category: 'Hardware',
    region: 'Sea-to-Sky',
    city: 'Powell River',
    address: '4420 Joyce Ave',
    phone: '604-485 2711',
    fit: 'Sunshine Coast North dealer store.',
  },
  {
    id: 161,
    name: 'Beachcomber Marina Store',
    category: 'Marina',
    region: 'Sea-to-Sky',
    city: 'Nanoose / Sechelt',
    address: '1220 Beachcomber Rd',
    phone: '604-885-2233',
    fit: 'Coastal marina store.',
  },
  {
    id: 162,
    name: "Sewell's Marina Store",
    category: 'Marina',
    region: 'Sea-to-Sky',
    city: 'Horseshoe Bay',
    address: '6695 Nelson Ave',
    phone: '604-921-3474',
    fit: 'Ferry terminal marina shop selling boater apparel.',
  },
  {
    id: 163,
    name: 'Horseshoe Bay Gift Shop',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'West Vancouver',
    address: '6405 Bay St',
    phone: '604-921-2211',
    fit: 'High foot-traffic ferry terminal tourist store.',
  },
  {
    id: 164,
    name: 'Bowen Island Marina Store',
    category: 'Marina',
    region: 'Sea-to-Sky',
    city: 'Bowen Island',
    address: '430 Bowen Island Trunk Rd',
    phone: '604-947-2244',
    fit: 'Snug Cove marina retail store.',
  },
  {
    id: 165,
    name: 'Bowen Island General Store',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'Bowen Island',
    address: '540 Dorman Rd',
    phone: '604-947-2121',
    fit: 'Island tourist shop selling humor tees.',
  },
  {
    id: 166,
    name: 'Squamish Chief Gifts',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'Squamish',
    address: '38012 Cleveland Ave',
    phone: '604-892 2211',
    fit: 'Downtown Squamish gift shop.',
  },
  {
    id: 167,
    name: 'Whistler Alpine Gifts',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'Whistler',
    address: '4154 Village Green',
    phone: '604-938-1122',
    fit: 'Resort village souvenir shop.',
  },
  {
    id: 168,
    name: 'Pemberton General Store',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'Pemberton',
    address: '7420 Prospect St',
    phone: '604-894-3311',
    fit: 'Valley gift store serving locals and tourists.',
  },
  {
    id: 169,
    name: 'Egmont Marina Resort Store',
    category: 'Marina',
    region: 'Sea-to-Sky',
    city: 'Egmont',
    address: '6702 Bathgate Rd',
    phone: '604-883 2221',
    fit: 'Skookumchuck Narrows boat store.',
  },
  {
    id: 170,
    name: 'Lund Harbour Marina Store',
    category: 'Marina',
    region: 'Sea-to-Sky',
    city: 'Lund',
    address: '1601 Hwy 101',
    phone: '604-483 4411',
    fit: 'Mile 0 Highway 101 marina shop.',
  },
  {
    id: 171,
    name: 'Whistler Outfitters & Gifts',
    category: 'Resort Gift',
    region: 'Sea-to-Sky',
    city: 'Whistler',
    address: '4314 Main St',
    phone: '604-932-4422',
    fit: 'Main Street resort shop selling mountain life tees and caps.',
  },
  {
    id: 172,
    name: 'Sunshine Coast Golf & Country Club',
    category: 'Golf',
    region: 'Sea-to-Sky',
    city: 'Roberts Creek',
    address: '3232 Sunshine Coast Hwy',
    phone: '604-885-9212',
    fit: 'Public course pro shop serving active retirees.',
  },
  {
    id: 173,
    name: 'Myrtle Point Golf Club',
    category: 'Golf',
    region: 'Sea-to-Sky',
    city: 'Powell River',
    address: '2865 McCausland Rd',
    phone: '604-487-4653',
    fit: 'Les Furber course with active senior golf membership.',
  },
  {
    id: 174,
    name: 'Bowen Island Golf Club',
    category: 'Golf',
    region: 'Sea-to-Sky',
    city: 'Bowen Island',
    address: '810 Bowena Dr',
    phone: '604-947-9383',
    fit: 'Island course pro shop popular with local retired residents.',
  },
  {
    id: 175,
    name: 'Sechelt Golf & Country Club',
    category: 'Golf',
    region: 'Sea-to-Sky',
    city: 'Sechelt',
    address: '6140 Sunshine Coast Hwy',
    phone: '604-885-4800',
    fit: 'Sunshine Coast golf shop catering to senior players.',
  },

  // Kootenays & Columbia-Shuswap (176 - 215)
  {
    id: 176,
    name: 'Revelstoke Golf Club',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Revelstoke',
    address: '171 Columbia Park Rd',
    phone: '250-837-4276',
    fit: 'Historic Columbia River course pro shop.',
  },
  {
    id: 177,
    name: 'Balfour Golf Course',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Balfour',
    address: '602 Queens Bay Rd',
    phone: '250-229-4231',
    fit: 'Scenic Kootenay Lake course pro shop with active senior leagues.',
  },
  {
    id: 178,
    name: 'Kokanee Springs Golf Resort',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Crawford Bay',
    address: '16082 Hwy 3A',
    phone: '250-227-9226',
    fit: 'Famous resort course pro shop carrying lifestyle apparel.',
  },
  {
    id: 179,
    name: 'Granite Point Golf Club',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Nelson',
    address: '1123 Rosemont Ave',
    phone: '250-352-2738',
    fit: 'Nelson course with high volume pro shop sales.',
  },
  {
    id: 180,
    name: 'Castlegar Golf Club',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Castlegar',
    address: '1602 Aaron Hill Rd',
    phone: '250-365-5006',
    fit: 'Championship course serving West Kootenay golfers.',
  },
  {
    id: 181,
    name: 'Redstone Golf Resort',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Rossland',
    address: '204 Redstone Dr',
    phone: '250-362-9141',
    fit: 'Les Furber signature course with resort pro shop.',
  },
  {
    id: 182,
    name: 'Fernie Golf Club',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Fernie',
    address: '201 Fairway Dr',
    phone: '250-423-7773',
    fit: 'Rocky Mountain course pro shop carrying casual resort wear.',
  },
  {
    id: 183,
    name: 'Cranbrook Golf Club',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Cranbrook',
    address: '2700 2nd St S',
    phone: '250-426-6462',
    fit: 'Established club with high senior membership.',
  },
  {
    id: 184,
    name: 'Wildstone Golf Course',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Cranbrook',
    address: '950 Wildstone Dr',
    phone: '250-489-1282',
    fit: 'Gary Player design public course pro shop.',
  },
  {
    id: 185,
    name: 'Shadow Mountain Golf Course',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Cranbrook',
    address: '7150 Shadow Mountain Way',
    phone: '250-426-3306',
    fit: 'Resort course pro shop stocking graphic tees and hats.',
  },
  {
    id: 186,
    name: 'Bootleg Gap Golf',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Kimberley',
    address: '1750 304th St',
    phone: '250-427-7077',
    fit: 'St. Mary River course carrying casual golf wear.',
  },
  {
    id: 187,
    name: 'Nelson Home Hardware Building Centre',
    category: 'Hardware',
    region: 'Kootenays',
    city: 'Nelson',
    address: '101 McDonald Dr',
    phone: '250-352-1919',
    fit: 'Kootenay dealer carrying housewares, clothing, and gifts.',
  },
  {
    id: 188,
    name: 'Castlegar Home Hardware',
    category: 'Hardware',
    region: 'Kootenays',
    city: 'Castlegar',
    address: '1960 Columbia Ave',
    phone: '250-365-3388',
    fit: 'Busy dealer store serving trades, boaters, and retirees.',
  },
  {
    id: 189,
    name: 'Trail Home Hardware',
    category: 'Hardware',
    region: 'Kootenays',
    city: 'Trail',
    address: '876 Victoria St',
    phone: '250-364-1311',
    fit: 'Downtown dealer with loyal active senior male customer base.',
  },
  {
    id: 190,
    name: 'Cranbrook Home Hardware Building Centre',
    category: 'Hardware',
    region: 'Kootenays',
    city: 'Cranbrook',
    address: '1901 McPhee Rd',
    phone: '250-426-6288',
    fit: 'Major regional dealer with dedicated workwear section.',
  },
  {
    id: 191,
    name: 'Fernie Home Building Centre',
    category: 'Hardware',
    region: 'Kootenays',
    city: 'Fernie',
    address: '1492 Hwy 3',
    phone: '250-423-4667',
    fit: 'Mountain town dealer catering to outdoorsmen and DIYers.',
  },
  {
    id: 192,
    name: 'Invermere Home Hardware Building Centre',
    category: 'Hardware',
    region: 'Kootenays',
    city: 'Invermere',
    address: '1310 7th Ave',
    phone: '250-342-6908',
    fit: 'Resort lake dealer stocking tools, boating gear, and gifts.',
  },
  {
    id: 193,
    name: 'Golden Home Hardware',
    category: 'Hardware',
    region: 'Kootenays',
    city: 'Golden',
    address: '802 10th Ave S',
    phone: '250-344-5258',
    fit: 'Highway dealer store serving mountain community.',
  },
  {
    id: 194,
    name: 'Revelstoke Home Hardware',
    category: 'Hardware',
    region: 'Kootenays',
    city: 'Revelstoke',
    address: '201 Campbell Ave',
    phone: '250-837-5115',
    fit: 'Downtown dealer carrying casual clothing and gifts.',
  },
  {
    id: 195,
    name: 'Creston Home Hardware',
    category: 'Hardware',
    region: 'Kootenays',
    city: 'Creston',
    address: '1608 NW Blvd',
    phone: '250-428-9388',
    fit: "Agricultural valley dealer with strong men's gift section.",
  },
  {
    id: 196,
    name: 'Balfour Resort & Marina Store',
    category: 'Marina',
    region: 'Kootenays',
    city: 'Balfour',
    address: '7887 Hwy 3A',
    phone: '250-229-4211',
    fit: 'Kootenay Lake ferry terminal store selling boat apparel.',
  },
  {
    id: 197,
    name: 'Kaslo Shipyard Marina Store',
    category: 'Marina',
    region: 'Kootenays',
    city: 'Kaslo',
    address: '201 Front St',
    phone: '250-353-2686',
    fit: 'Historic lakefront marina with nautical retail shop.',
  },
  {
    id: 198,
    name: 'Sunshine Marina Store',
    category: 'Marina',
    region: 'Kootenays',
    city: 'Sunshine Bay',
    address: '5451 Hwy 3A',
    phone: '250-229-4112',
    fit: 'Kootenay Lake marina carrying boating t-shirts and caps.',
  },
  {
    id: 199,
    name: 'Christina Lake Marina Store',
    category: 'Marina',
    region: 'Kootenays',
    city: 'Christina Lake',
    address: '180 East Lake Dr',
    phone: '250-447-9273',
    fit: 'Prime summer lake store selling boat apparel and novelties.',
  },
  {
    id: 200,
    name: 'Fairmont Hot Springs Resort Shop',
    category: 'Resort Gift',
    region: 'Kootenays',
    city: 'Fairmont Hot Springs',
    address: '5225 Fairmont Resort Rd',
    phone: '250-345-6000',
    fit: 'Resort village boutique selling resort lifestyle clothing.',
  },
  {
    id: 201,
    name: 'Radium Hot Springs Gift Shop',
    category: 'Resort Gift',
    region: 'Kootenays',
    city: 'Radium Hot Springs',
    address: '7556 Main St W',
    phone: '250-347-9331',
    fit: 'High foot-traffic tourist store with humor t-shirts.',
  },
  {
    id: 202,
    name: 'Nelson General Store & Gifts',
    category: 'Resort Gift',
    region: 'Kootenays',
    city: 'Nelson',
    address: '402 Baker St',
    phone: '250-352-3311',
    fit: 'Baker Street tourist store carrying Canadian humor apparel.',
  },
  {
    id: 203,
    name: 'Fernie General Store',
    category: 'Resort Gift',
    region: 'Kootenays',
    city: 'Fernie',
    address: '561 2nd Ave',
    phone: '250-423-3322',
    fit: 'Historic downtown store with mountain life graphic tees.',
  },
  {
    id: 204,
    name: 'Kimberley Platzl Gifts',
    category: 'Resort Gift',
    region: 'Kootenays',
    city: 'Kimberley',
    address: '180 Howard St',
    phone: '250-427-3311',
    fit: 'Pedestrian mall boutique selling novelties and caps.',
  },
  {
    id: 205,
    name: 'Revelstoke General Store',
    category: 'Resort Gift',
    region: 'Kootenays',
    city: 'Revelstoke',
    address: '301 MacKenzie Ave',
    phone: '250-837-3322',
    fit: 'Mountain tourist shop selling graphic tees and gifts.',
  },
  {
    id: 206,
    name: 'Kaslo General Store',
    category: 'Resort Gift',
    region: 'Kootenays',
    city: 'Kaslo',
    address: '404 Front St',
    phone: '250-353-2211',
    fit: 'Heritage main street shop selling local lifestyle clothing.',
  },
  {
    id: 207,
    name: 'Golden Trading Post',
    category: 'Resort Gift',
    region: 'Kootenays',
    city: 'Golden',
    address: '510 9th Ave N',
    phone: '250-344-3311',
    fit: 'Highway tourist shop carrying outdoor graphic apparel.',
  },
  {
    id: 208,
    name: 'Creston Valley Gifts',
    category: 'Resort Gift',
    region: 'Kootenays',
    city: 'Creston',
    address: '1130 Canyon St',
    phone: '250-428-3322',
    fit: 'Downtown valley store selling funny tees and gifts.',
  },
  {
    id: 209,
    name: 'Windermere Valley Golf Course',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Windermere',
    address: '1881 Windermere Loop Rd',
    phone: '250-342-3004',
    fit: 'Friendly public course pro shop in Lake Windermere.',
  },
  {
    id: 210,
    name: 'Copper Point Golf Club',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Invermere',
    address: '651 Hwy 93/95',
    phone: '250-341-3392',
    fit: '36-hole resort course with premier golf pro shop.',
  },
  {
    id: 211,
    name: 'The Springs at Radium Golf Course',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Radium Hot Springs',
    address: '8147 Golf Course Rd',
    phone: '250-347-6200',
    fit: 'Championship course shop in tourist hot spot.',
  },
  {
    id: 212,
    name: 'Trickle Creek Golf Resort',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Kimberley',
    address: '5000 Stemwinder Dr',
    phone: '250-427-5171',
    fit: 'Resort course pro shop carrying casual golf wear.',
  },
  {
    id: 213,
    name: 'Kimberley Golf Club',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Kimberley',
    address: '415 302nd St',
    phone: '250-427-4161',
    fit: 'Historic 1924 course with active senior membership.',
  },
  {
    id: 214,
    name: 'St. Eugene Golf Resort Shop',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Cranbrook',
    address: '7777 Mission Road',
    phone: '250-420-2060',
    fit: 'Resort destination pro shop with extensive retail.',
  },
  {
    id: 215,
    name: 'Creston Golf Club',
    category: 'Golf',
    region: 'Kootenays',
    city: 'Creston',
    address: '1800 Mallory Rd',
    phone: '250-428-5515',
    fit: 'Scenic valley pro shop serving local retirees.',
  },

  // Lower Mainland / Fraser Valley (216 - 250)
  {
    id: 216,
    name: 'Chilliwack Golf Club',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Chilliwack',
    address: '41894 Yale Rd W',
    phone: '604-823-4544',
    fit: "Fraser Valley club pro shop selling men's lifestyle apparel.",
  },
  {
    id: 217,
    name: 'Steveston Marine & Hardware',
    category: 'Marina',
    region: 'Fraser Valley',
    city: 'Steveston',
    address: '3800 Moncton St',
    phone: '604-277-7031',
    fit: 'Waterfront store carrying boater rainwear, hats, and gifts.',
  },
  {
    id: 218,
    name: 'Cultus Lake Golf Club',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Lindell Beach',
    address: '4000 Columbia Valley Hwy',
    phone: '604-858-6861',
    fit: 'Resort lake course pro shop with high casual wear turn.',
  },
  {
    id: 219,
    name: 'Sandpiper Golf Course',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Harrison Mills',
    address: '14282 Morris Valley Rd',
    phone: '604-796-1000',
    fit: 'Resort course on Harrison River popular with retirees.',
  },
  {
    id: 220,
    name: 'Ledgeview Golf Club',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Abbotsford',
    address: '35997 McKee Rd',
    phone: '604-852-2250',
    fit: 'Famous Fraser Valley course with busy pro shop.',
  },
  {
    id: 221,
    name: 'Fraser Glen Golf Course',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Abbotsford',
    address: '36036 S Parallel Rd',
    phone: '604-852-3477',
    fit: 'Executive course popular with active senior golfers.',
  },
  {
    id: 222,
    name: 'Pagoda Ridge Golf Course',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Langley',
    address: '7888 264th St',
    phone: '604-856-0929',
    fit: 'High volume public course carrying casual golf wear.',
  },
  {
    id: 223,
    name: 'Redwoods Golf Course',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Langley',
    address: '22011 88th Ave',
    phone: '604-882-5132',
    fit: 'Top public course in Fraser Valley with active pro shop.',
  },
  {
    id: 224,
    name: 'Belmont Golf Course',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Langley',
    address: '24180 72nd Ave',
    phone: '604-534-8588',
    fit: 'Fraserglen area public course serving senior golfers.',
  },
  {
    id: 225,
    name: 'Fort Langley Golf Club',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Fort Langley',
    address: '9782 McKinnon Rd',
    phone: '604-888-2829',
    fit: 'Historic town golf course with popular pro shop.',
  },
  {
    id: 226,
    name: 'Peace Portal Golf Club',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Surrey',
    address: '16900 4th Ave',
    phone: '604-538-4818',
    fit: "Border course with active senior men's leagues.",
  },
  {
    id: 227,
    name: 'Hazelmere Golf & Tennis Club',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Surrey',
    address: '18150 8th Ave',
    phone: '604-538-1212',
    fit: 'Country club facility with well-stocked apparel shop.',
  },
  {
    id: 228,
    name: 'Morgan Creek Golf Course',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Surrey',
    address: '3500 Morgan Creek Way',
    phone: '604-537-4653',
    fit: 'Premier public course with large retail pro shop.',
  },
  {
    id: 229,
    name: 'Kings Links by the Sea',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Delta',
    address: '3388 72nd St',
    phone: '604-946-1838',
    fit: 'Coastal links course pro shop carrying wind/boating wear.',
  },
  {
    id: 230,
    name: 'Beach Grove Golf Club',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Tsawwassen',
    address: '5946 12th Ave',
    phone: '604-943-1155',
    fit: 'Sunny Tsawwassen private club with senior membership.',
  },
  {
    id: 231,
    name: 'Delta Golf Course',
    category: 'Golf',
    region: 'Fraser Valley',
    city: 'Delta',
    address: '11550 Ladner Trunk Rd',
    phone: '604-594-1414',
    fit: 'Popular executive course pro shop.',
  },
  {
    id: 232,
    name: 'Chilliwack Home Hardware Building Centre',
    category: 'Hardware',
    region: 'Fraser Valley',
    city: 'Chilliwack',
    address: '45715 Hocking Ave',
    phone: '604-792-1311',
    fit: 'Major Fraser Valley dealer with large workwear aisle.',
  },
  {
    id: 233,
    name: 'Abbotsford Home Hardware',
    category: 'Hardware',
    region: 'Fraser Valley',
    city: 'Abbotsford',
    address: '2392 Clearbrook Rd',
    phone: '604-853-2228',
    fit: 'Independent dealer store serving local trades and homeowners.',
  },
  {
    id: 234,
    name: 'Mission Home Hardware',
    category: 'Hardware',
    region: 'Fraser Valley',
    city: 'Mission',
    address: '33171 1st Ave',
    phone: '604-826-2741',
    fit: 'Main street dealer carrying tools, workwear, and novelties.',
  },
  {
    id: 235,
    name: 'Ladner Home Hardware',
    category: 'Hardware',
    region: 'Fraser Valley',
    city: 'Ladner',
    address: '4837 Delta St',
    phone: '604-946-1101',
    fit: 'Heritage village dealer store with active senior clientele.',
  },
  {
    id: 236,
    name: 'White Rock Home Hardware',
    category: 'Hardware',
    region: 'Fraser Valley',
    city: 'White Rock',
    address: '15175 Russell Ave',
    phone: '604-531-2321',
    fit: "Resort beach community dealer with men's gifts.",
  },
  {
    id: 237,
    name: 'Maple Ridge Home Hardware',
    category: 'Hardware',
    region: 'Fraser Valley',
    city: 'Maple Ridge',
    address: '22250 Dewdney Trunk Rd',
    phone: '604-463-4181',
    fit: 'Established dealer store with outdoor supply section.',
  },
  {
    id: 238,
    name: "Buckerfield's Abbotsford",
    category: 'Hardware',
    region: 'Fraser Valley',
    city: 'Abbotsford',
    address: '31852 Marshall Rd',
    phone: '604-855-3831',
    fit: 'High volume country store selling rugged apparel and caps.',
  },
  {
    id: 239,
    name: "Buckerfield's Chilliwack",
    category: 'Hardware',
    region: 'Fraser Valley',
    city: 'Chilliwack',
    address: '44140 Luckakuck Way',
    phone: '604-792-0858',
    fit: 'Farm store carrying workwear, hats, and gifts.',
  },
  {
    id: 240,
    name: 'Peavey Mart Chilliwack',
    category: 'Hardware',
    region: 'Fraser Valley',
    city: 'Chilliwack',
    address: '45150 Luckakuck Way',
    phone: '604-792-2000',
    fit: 'Major farm and ranch supply store stocking graphic apparel.',
  },
  {
    id: 241,
    name: 'Steveston Waterfront Store & Gifts',
    category: 'Resort Gift',
    region: 'Fraser Valley',
    city: 'Steveston',
    address: '3911 Moncton St',
    phone: '604-272-3311',
    fit: 'High tourist traffic fishing village shop.',
  },
  {
    id: 242,
    name: 'Fort Langley Trading Co.',
    category: 'Resort Gift',
    region: 'Fraser Valley',
    city: 'Fort Langley',
    address: '9203 Glover Rd',
    phone: '604-888-3322',
    fit: "Historic village boutique selling men's lifestyle clothing.",
  },
  {
    id: 243,
    name: 'Harrison Hot Springs Resort Shop',
    category: 'Resort Gift',
    region: 'Fraser Valley',
    city: 'Harrison Hot Springs',
    address: '100 Esplanade Ave',
    phone: '604-796-2244',
    fit: 'Lake resort shop with vacation apparel.',
  },
  {
    id: 244,
    name: 'Sasquatch Country Gifts',
    category: 'Resort Gift',
    region: 'Fraser Valley',
    city: 'Harrison Hot Springs',
    address: '234 Esplanade Ave',
    phone: '604-796-3311',
    fit: 'Lakefront tourist store with humor graphic tees.',
  },
  {
    id: 245,
    name: 'Hope Trading Post',
    category: 'Resort Gift',
    region: 'Fraser Valley',
    city: 'Hope',
    address: '330 Wallace St',
    phone: '604-869-3322',
    fit: 'Highway crossroads stop selling novelty apparel and gifts.',
  },
  {
    id: 246,
    name: 'White Rock Beach Gifts',
    category: 'Resort Gift',
    region: 'Fraser Valley',
    city: 'White Rock',
    address: '14971 Marine Dr',
    phone: '604-531-3322',
    fit: 'Oceanside promenade store with summer clothing.',
  },
  {
    id: 247,
    name: 'Crescent Beach Trading Co.',
    category: 'Resort Gift',
    region: 'Fraser Valley',
    city: 'Surrey',
    address: '12160 Beecher St',
    phone: '604-538-3311',
    fit: 'Beachfront store selling casual coastal wear.',
  },
  {
    id: 248,
    name: 'Mission Waterfront Store',
    category: 'Resort Gift',
    region: 'Fraser Valley',
    city: 'Mission',
    address: '33201 1st Ave',
    phone: '604-820-3322',
    fit: 'Fraser River town store selling outdoorsmen gifts.',
  },
  {
    id: 249,
    name: 'Fort Langley Village Antiques & Gifts',
    category: 'Resort Gift',
    region: 'Fraser Valley',
    city: 'Fort Langley',
    address: '9188 Glover Rd',
    phone: '604-888-1112',
    fit: 'Busy weekend tourist stop with vintage humor tees.',
  },
];
